name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:

    - name: Check out
      uses: actions/checkout@v2

    # actions:

    - name: Install Deno
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh
        export DENO_INSTALL="~/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"

    - name: Run tests
      run: |
        deno test
